# Mod that makes symbol encounters (visible overworld spawns) pull from the hidden encounter spawn table
[underworld]
active = false

# Mod that makes shiny pokemon visible in the overworld
[overworld_shiny]
active = false

# some sounds:
# "Play_Ba_sys_rare_effect" (battle shiny sound)
# "Play_Audience_cheer_riser_rnd"
# "Play_UI_netbattle_rank_up"
# "Play_UI_Lcircuit_Goal"
# "Play_Camp_Cooking_Explosion"
# set to "" for no sound
sound = "Play_Ba_sys_rare_effect"
# some particles:
# "bin/field/effect/particle/particle/ef_poke_symbol_aura.ptcl" (brilliant aura)
# "bin/field/effect/particle/ef_cyc_aura/ef_cyc_aura_rare_bk.ptcl" (squares from the black bike)
# "bin/field/effect/particle/ef_cyc_aura/ef_cyc_aura_rare_wh.ptcl" (stars from the white bike)
# set to "" for no particle
shiny_ptcl = "bin/field/effect/particle/ef_cyc_aura/ef_cyc_aura_rare_bk.ptcl"
# whether or not brilliant spawns show their aura
show_aura_for_brilliants = true
# whether or not to load the battle sound bank in the overworld (needed for battle shiny sound)
include_battle_sounds = true
# whether or not to play the shiny sound when the following pokemon respawns
play_sound_for_following = false
# whether or not to show the shiny particle for the following pokemon
show_ptcl_for_following = true
# whether or not to show a message box on screen when a shiny spawns
show_message_box = false
# 0 for regular shiny rate, [1,100] for modified rate
boosted_percentage = 70

# Mod that actively randomizes every new spawn
[randomizer]
active = false

# Mod that lets you tweak the camera speed, pitch range, and field of view
[camera_tweaks]
active = false

# camera speed in degrees per time unit
adjustment_speed = 3.75
# min pitch in degrees
min_pitch = -71.6197244
# max pitch in degrees
max_pitch = 14.3239449
# base camera distance
min_distance = 450.0
# zoomed out camera distance
max_distance = 1000.0

# Mod that removes the level cap-based shiny lock & catch lock
[uncap_level]
active = false

# remove all badge-based level caps (if false, shiny uncatchables are possible)
fully = true

# Mod that allows detaching the camera from the player and moving it on its own
[freecam]
active = false
disable_terrain_culling = true
# forces the extended camera to be active by default
always_use_extended_camera = false

# Mod that overwrites the maximum symbol encounter spawn count for spawners in glimwood tangle
[glimwood_overworld]
active = false

# maximum symbol count per spawner
maximum_spawns = 1

# Mod that allows you to pilot your following pokemon
[synchro_mode]
active = false

# Mod that allows following pokemon in the galar mainland wild area
[extended_following]
active = false

# Mod that tweaks fishing mechanics
[fishing_tweaks]
active = false

# whether or not to retain fishing chains after brilliant pokemon spawn
keep_chain_after_brilliant = true

# Mod allows cycling dex animations
[dex_animations]
active = false